apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter-service
  labels:
    app: mysql-exporter

spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9104
    targetPort: 9104
  selector:
    app: mysql