apiVersion: v1
kind: Pod
metadata:
  name: tolerated-pod
spec:
  tolerations:
   - key: "key"
     operator: "Equal"
     value: "gpu"
     effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx