apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
    org: gfg
    dc: mumbai
    maintainer: sudhanshu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template: #pod template
    metadata:
      name: mongodb
      labels:
        app: mongo
    spec: #pod specification
      containers:
      - name: mongo-db
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-volume
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc