apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: mycontainer
        image: jinny1/mario-game
        resources:
          requests: 
            memory: "30Mi"
          limits:
            memory: "50Mi"