apiVersion: apps/v1
kind: Deployment
metadata:
  name: "deploymentv1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "gfgapp"
  template:
    metadata:
      name: "mypod"
      labels:
        app: "gfgapp"
        city: "delhi"
    spec:
      containers:
        - name: "myos"
          image: jinny1/gfg30sampleapp:v1